platform :ios, '9.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'ZLGitHubClient' do

# 日志打印
pod 'CocoaLumberjack'
pod 'CocoaLumberjack/Swift'

# Http
pod 'AFNetworking'

# 数据库
pod 'FMDB'

# Json Model 转换
pod 'MJExtension'

# 刷新控件
pod 'MJRefresh'

#下载图片
pod 'SDWebImage', '~> 5.0.0'

pod 'MMMarkdown'

# AutoLayout
pod 'Masonry'
pod 'SnapKit', '~> 4.0.0'

pod 'YYText'

# 移动监控工具
pod 'LookinServer', :configurations => ['Debug']
pod 'DoraemonKit/Core', '~> 2.0.0', :configurations => ['Debug']
pod 'DoraemonKit/WithLogger', '~> 2.0.0', :configurations => ['Debug']
#pod 'DoraemonKit/WithGPS', '~> 2.0.0', :configurations => ['Debug']
pod 'DoraemonKit/WithMLeaksFinder', '2.0.0', :configurations => ['Debug']

# bugly
pod 'Bugly'
end
