platform :ios, '9.0'
use_frameworks!

target 'ZLGitHubClient' do

# 日志打印
pod 'CocoaLumberjack'
pod 'CocoaLumberjack/Swift'

# Http
pod 'AFNetworking'

# 数据库
pod 'FMDB'

# Json Model 转换
pod 'MJExtension'

pod 'SDWebImage', '~> 5.0.0'

pod 'MMMarkdown'

end
