# action 语法 https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ZLGithub Build

on:                               # 触发条件
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: macos-latest # runner 系统 
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
      with: 
        ref: master 
    - name: construct build enviroment
      working-directory: ./ZLGitHubClient          # 指定run 的工作目录
      run: |
        echo "start constructing build enviroment"
        gem cleanup
        gem install bundler
        bundle install
        pod repo update
        pod install
    - name: archive app
      working-directory: ./ZLGitHubClient          # 指定run 的工作目录
      env: 
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_URL: ${{ secrets.MATCH_GITHUB_URL }}
      run: |
        pwd 
        bundle exec fastlane github_action_adhoc
