# action 语法 https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Build Check 仅在提交后做编译检查
name: ZLGithub Build Check 

on:                               # 触发条件
  push:
    branches-ignore:
      - master
      - develop
      - release

jobs:
  build:
    name: build
    runs-on: macos-latest # runner 系统 
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
      with: 
        ref: ${{ GITHUB_REF }}  # 默认是切到出发workflow的节点
    - name: construct build enviroment
      working-directory: ./ZLGitHubClient          # 指定run 的工作目录
      run: |
        git rev-parse HEAD
        git rev-parse --abbrev-ref HEAD
        echo "start construct build enviroment"
        gem cleanup
        gem install bundler
        bundle install
        bundle exec pod repo update
        bundle exec pod install
        echo "construct build enviroment success"
    - name: build app
      working-directory: ./ZLGitHubClient          # 指定run 的工作目录
      env: 
        MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GITHUB_URL: ${{ secrets.MATCH_GITHUB_URL }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.apple_pwd }}   # pwd for upload to testflight 
        FASTLANE_USER: ${{ secrets.FASTLANE_USER }}                                    
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }} 
      run: |
        echo "start project build check"
        bundle exec fastlane github_action_build_check
        echo "project build success"
