name: ZLGithub Test

on: [push,pull_request]

jobs:
  build:
    name: build
    runs-on: macos-latest # runner 系统 
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: email send for success
      working-directory: ./ZLGitHubClient/EmailSender
      if: ${{ always() }}
      env: 
        JOB_STATUS: ${{ success() }}
        NOREPLEY_PWD: ${{ secrets.NOREPLY_PASSWD }}
        Email_Receivers: ${{ secrets.Email_Receivers }}
      run: |
        python3 BuildCheckEmailSender.py $NOREPLEY_PWD $Email_Receivers $JOB_STATUS
